[local]
base_dir = ~/shared/POINTEX21/CAFEDEROME
store_id = 2
log_file = ./db_mb_watcher.log
status_file = caisse_status.txt

[api]
url = http://app.storeyes.io:8000/process
delta_hour = 2
timeout = 120

[watcher]
sleep_interval = 10
stable_seconds = 2

[mqtt]
host = 18.100.207.236
port = 1883
user = storeyes
password = 12345
topic =
qos = 1
retain = false
timeout = 5
retries = 3
