[local]
base_dir = ~/shared/POINTEX21/CAFEDEROME
log_dir = ./logs
status_file = caisse_status.txt

[api]
url = http://app.storeyes.io:9000/process
timeout = 120

[watcher]
sleep_interval = 10
stable_seconds = 1

[mqtt]
host = mqtt.storeyes.io
port = 1883
user = storeyes
password = 12345
qos = 1
retain = false
timeout = 5
retries = 3
